### ISSUE TITLE
create workflow to update ss3sim/ssmse with latest release exes

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/workflows#6]
related to https://github.com/ss3sim/ss3sim/issues/335 . It would be nice to automate this, as we are often slow to do this.

**Comment by k-doering-NOAA** [comment]
Steps:
1. checkout repo where to put the exes
2.  download the exes from github releases
3.  put the exes in the correct location
4. make sure mac and linux exes have ok permissions (chmod a+x)
5. submit this change as a PR, naming with the version of ss3

**Comment by k-doering-NOAA** [comment]
An initial version is currently in a branch. Here is the [current file](https://github.com/nmfs-stock-synthesis/workflows/blob/ss3-version/.github/workflows/update-ss3-version.yml) Here's what the PR looks like, roughly: https://github.com/nmfs-stock-synthesis/workflows/pull/29

@kellijohnson-NOAA  Are there other steps you want to add besides what is outlined in [this comment](https://github.com/nmfs-stock-synthesis/workflows/issues/6#issuecomment-1030073677)?

One thought I had was we could bump the version in the DESCRIPTION file. I think it would also be a good idea to run r cmd check on the branch.

Also, looking now if there is a way for us to trigger this build to occur when there is a new release in the SS3 repo. I think there likely is.

**Comment by k-doering-NOAA** [comment]
Actually, I think now the easiest way to trigger the workflow would just be manually with the push of a button. It sounds complicated to set up triggering the build to occur when there is a new SS3 release, so it seems far simpler to use workflow_dispatch.

Here is the file I think we can put in .github/workflows (maybe called call-update-ss3-version.yml):

```yml
# update ss3 binaries using reusable workflow
name: update ss3 version
on:
  workflow_dispatch:
jobs:
  call-update-ss3:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/update-ss3-version.yml@main
```
